// Package docs GENERATED BY SWAG; DO NOT EDIT
package docs

import "github.com/swaggo/swag"

var docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfo holds exported Swagger Info
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:            "localhost:8080",
	BasePath:        "/api",
	Schemes:         []string{"http"},
	Title:           "Dorm Management API",
	Description:     "API สำหรับระบบจัดการหอพัก",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
} 